# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.eval_bases <- function(bases_list, Z_mat, activation_option, intercept_option, probit = FALSE, verbose = TRUE, print_every = 50L) {
    .Call('_ridgeBART_eval_bases', PACKAGE = 'ridgeBART', bases_list, Z_mat, activation_option, intercept_option, probit, verbose, print_every)
}

.get_bases <- function(fit_list, tX_cont, tX_cat, tZ_mat, probit = FALSE, verbose = TRUE, print_every = 50L) {
    .Call('_ridgeBART_get_bases', PACKAGE = 'ridgeBART', fit_list, tX_cont, tX_cat, tZ_mat, probit, verbose, print_every)
}

.predict_ridgeBART <- function(fit_list, tX_cont, tX_cat, tZ_mat, probit = FALSE, verbose = TRUE, print_every = 50L) {
    .Call('_ridgeBART_predict_ridgeBART', PACKAGE = 'ridgeBART', fit_list, tX_cont, tX_cat, tZ_mat, probit, verbose, print_every)
}

.probit_ridgeBART_fit <- function(Y_train, tX_cont_train, tX_cat_train, tZ_mat_train, tX_cont_test, tX_cat_test, tZ_mat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, p_change, beta0, tau, branch_alpha, branch_beta, activation_option, intercept_option, sparse_smooth_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_ridgeBART_probit_ridgeBART_fit', PACKAGE = 'ridgeBART', Y_train, tX_cont_train, tX_cat_train, tZ_mat_train, tX_cont_test, tX_cat_test, tZ_mat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, p_change, beta0, tau, branch_alpha, branch_beta, activation_option, intercept_option, sparse_smooth_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

.ridgeBART_fit <- function(Y_train, tX_cont_train, tX_cat_train, tZ_mat_train, tX_cont_test, tX_cat_test, tZ_mat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, p_change, beta0, tau, branch_alpha, branch_beta, sigma0, lambda, nu, activation_option, intercept_option, sparse_smooth_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, nd, burn, thin, save_samples, save_trees, verbose, print_every) {
    .Call('_ridgeBART_ridgeBART_fit', PACKAGE = 'ridgeBART', Y_train, tX_cont_train, tX_cat_train, tZ_mat_train, tX_cont_test, tX_cat_test, tZ_mat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, p_change, beta0, tau, branch_alpha, branch_beta, sigma0, lambda, nu, activation_option, intercept_option, sparse_smooth_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, nd, burn, thin, save_samples, save_trees, verbose, print_every)
}

.drawEnsemble <- function(tX_cont, tX_cat, tZ_mat, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, beta0, tau, lambda, nu, activation_option, intercept_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, verbose, print_every) {
    .Call('_ridgeBART_drawEnsemble', PACKAGE = 'ridgeBART', tX_cont, tX_cat, tZ_mat, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, oblique_option, prob_aa, x0_option, sparse, a_u, b_u, beta0, tau, lambda, nu, activation_option, intercept_option, n_bases, rho_option, rho_prior, rho_alpha, rho_nu, rho_lambda, M, verbose, print_every)
}

